env:
  es2020: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
  - import
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - prettier
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
rules:
  import/order:
    - warn
    - groups: [ builtin, external ]
      alphabetize:
        order: asc
        caseInsensitive: true